### PR TITLE
Fixed failure in proxy updates

### PR DESCRIPTION
**Pull request by ianradnor088**
We have fixed test case in drclient.service.spec.ts file

### CODE REVIEW

**Comment by mattbeattie** [comment]
It appears this does fix a test that was failing before, but the coverage drops below the threshold:

```
npm run test

> rosie-prototype@0.0.1 test
> ng test

⠙ Generating browser application bundles (phase: building)...11 04 2022 09:08:53.824:INFO [karma-server]: Karma v6.3.3 server started at http://localhost:9876/
11 04 2022 09:08:53.825:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
11 04 2022 09:08:53.827:INFO [launcher]: Starting browser ChromeHeadless
✔ Browser application bundle generation complete.
11 04 2022 09:08:57.842:INFO [Chrome Headless 100.0.4896.75 (Mac OS 10.15.7)]: Connected on socket rn5DQsjWvt6t5eFQAAAB with id 6092410
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 1 of 99 SUCCESS (0 secs / 0.006 secs)
11 04 2022 09:08:59.470:WARN [web-server]: 404: /_karma_webpack_/svg/reader-outline.svg
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 2 of 99 SUCCESS (0 secs / 0.037 secs)
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 3 of 99 SUCCESS (0 secs / 0.078 secs)
11 04 2022 09:08:59.524:WARN [web-server]: 404: /_karma_webpack_/svg/help-outline.svg
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 25 of 99 SUCCESS (0 secs / 0.169 secs)
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 26 of 99 SUCCESS (0 secs / 0.207 secs)
11 04 2022 09:08:59.665:WARN [web-server]: 404: /_karma_webpack_/svg/paper-plane-outline.svg
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 28 of 99 SUCCESS (0 secs / 0.286 secs)
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 30 of 99 SUCCESS (0 secs / 0.366 secs)
11 04 2022 09:08:59.828:WARN [web-server]: 404: /_karma_webpack_/svg/navigate-outline.svg
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 35 of 99 SUCCESS (0 secs / 0.572 secs)
11 04 2022 09:09:00.038:WARN [web-server]: 404: /_karma_webpack_/svg/documents-outline.svg
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 47 of 99 SUCCESS (0 secs / 1.024 secs)
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 49 of 99 SUCCESS (0 secs / 1.099 secs)
LOG: Object{first_csb_text: 'It looks like you didn't enter the ballot checking code in the VerifyMyBallot site.', second_csb_text: 'Tap Retry to try again. Be sure to enter the code into the VerifyMyBallot site before you tap the Code Entered button in this app.', third_csb_text: 'You can review the step-by-step instructions at', link_csb: 'electionwebsite.gov', back_btn_csb: 'retry'}
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 50 of 99 SUCCESS (0 secs / 1.139 secs)
LOG: Object{first_csb_text: 'It looks like you didn't enter the ballot checking code in the VerifyMyBallot site.', second_csb_text: 'Tap Retry to try again. Be sure to enter the code into the VerifyMyBallot site before you tap the Code Entered button in this app.', third_csb_text: 'You can review the step-by-step instructions at', link_csb: 'electionwebsite.goChrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 81 of 99 SUCCESS (0 secs / 1.379 secs)
11 04 2022 09:09:00.884:WARN [web-server]: 404: /_karma_webpack_/svg/close-circle-outline.svg
ERROR: 'NG0303: Can't bind to 'formGroup' since it isn't a known property of 'form'.'
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 91 of 99 SUCCESS (0 secs / 1.709 secs)
ERROR: 'NG0303: Can't bind to 'formGroup' since it isn't a known property of 'form'.'
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 98 of 99 SUCCESS (0 secs / 1.963 secs)
Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Executed 99 of 99 SUCCESS (2.148 secs / 2.008 secs)
TOTAL: 99 SUCCESS
11 04 2022 09:09:01.652:ERROR [coverage]: Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Coverage for branches (33.98%) does not meet global threshold (35%)
11 04 2022 09:09:01.652:ERROR [coverage]: Chrome Headless 100.0.4896.75 (Mac OS 10.15.7): Coverage for lines (64.65%) does not meet global threshold (65%)

=============================== Coverage summary ===============================
Statements   : 67.22% ( 601/894 )
Branches     : 33.98% ( 70/206 )
Functions    : 63.77% ( 243/381 )
Lines        : 64.65% ( 536/829 )
================================================================================
```

I suppose this is a failing on my part, since a lack of coverage does not actually result in an overall failing status code like it should.

**Comment by mattbeattie** [comment]
In the `ballot-checking-integration` branch, the failing test is in the `CheckYourPairingCodesPage` page. Somehow that page does exist in the `proxy-updates` branch, but does not have a failing test here.

Clearly there are some things about the 3 branches ( the 2 `proxy-updates` branches on the repo and on the `aion-dk` fork and the `ballot-checking-integration` branch on the `aion-dk` fork) that I don't understand. I'm honestly not sure if it's worth trying to do a post-mortem on the git histories on all 3 branches to try to figure out who did what, and where the failure was introduced.

Perhaps the easiest thing would be for Mads to simply disable any tests that are broken in his branch. It's not like the `CheckYourPairingCodesPage` test adds any value other than proving dependency injection works anyway.

**Comment by trustthevote** [comment]
At this point, expediency is more important than retrospective understanding. We need to get to a buildable version of Rosie (with AV's ballot-checking-integration branch mods) so that we can test it, fix as needed, and lock the code. Until we do that, can can't finalize the integration of Rosie code into MarkIt.

**Comment by mattbeattie** [comment]
@trustthevote agreed!

**Pull request merged**
